Normalize package names with lowercase
When a python package is listed multiple time but with uppercase/lowercase
changes then introspect sanitization won't handle it.
In db9e74a, only the underscore/dash scenario has been solved.
As a result, the assemble script will fail with a double requirement error.

ERROR: Double requirement given: Jinja2==3.0.3 (from -r /tmp/src/requirements.txt (line 40))
(already in jinja2>=2.8 (from -r /tmp/src/requirements.txt (line 12)), name='Jinja2')

While this isn't an issue for recent pip version, older versions with python
3.8 and 3.9 runtimes on RHEL 8 based distributions are affected by this.

This replaces the setuptools runtime usage by importlib.metadata which
provides builtin method to normalize package names.

Unlike pkg_resources.safe_name, the dash character is changed to underscore.

Closes: #408

https://packaging.python.org/en/latest/specifications/name-normalization

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>